In [5]:
import numpy as np
import pandas as pd

In [6]:
students = ["Pam", "Jim", "Michael", "Dwight", "Toby"]
courses = ["Math", "English", "Science"]

In [19]:
marks = np.random.randint(40,101, size = (len(students), len(courses)))
print(marks)

[[53 57 69]
 [46 52 41]
 [65 99 88]
 [53 71 55]
 [57 65 83]]


In [ ]:
avg_studnet = np.mean(marks, axis=1)
print(avg_studnet)

[59.66666667 46.33333333 84.         59.66666667 68.33333333]


In [21]:
avg_course = np.mean(marks, axis=0)
print(avg_course)

[54.8 68.8 67.2]


In [23]:
sd_studnet = np.std(marks, axis=1)
print(sd_studnet)

[ 6.79869268  4.49691252 14.16568624  8.05536398 10.87300429]


In [24]:
sum_grades = np.sum(marks, axis=1)
max_grades = np.max(sum_grades)
print(max_grades)

252


In [25]:
df = pd.DataFrame(marks, index= students, columns= courses)
print(df)

         Math  English  Science
Pam        53       57       69
Jim        46       52       41
Michael    65       99       88
Dwight     53       71       55
Toby       57       65       83


In [ ]:
avg_grades_persub = df.median(axis=0)
print(avg_grades_persub)

Math       53.0
English    65.0
Science    69.0
dtype: float64


In [34]:
totalscore = df.sum(axis=1)
student_highestscore = totalscore.idxmax() 
print(student_highestscore)

Michael


In [35]:
fail_student = df<50
failed_any = fail_student.any(axis=1)
total_failed_any = failed_any.sum()
print(total_failed_any)


1
